### ISSUE TITLE
增加数量较大的经验值后报错

### ISSUE THREAD

**Issue by Eplge627** [CPJiNan/AkariLevel#14]
最新版本4.0.6
当我输入/akarilevel exp Example Eplge627 100000000时报错并只升了两级，后面使用其他指令也报错，除了reload
`null
org.bukkit.command.CommandException: Unhandled exception executing command 'akarilevel' in plugin AkariLevel v4.0.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_421]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_421]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_421]
Caused by: javax.script.ScriptException: <eval>:1:5 Missing close quote
1400"
     ^ in <eval> at line number 1 at column number 5
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:496) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:182) ~[nashorn.jar:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common5.NashornCompilerKt.compileJS(NashornCompiler.kt:31) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.LevelAPI.getLvlExp(LevelAPI.kt:146) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.LevelAPI.getLevelExp(LevelAPI.kt:70) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.checkCondition(PlayerAPI.kt:324) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.refreshLevel(PlayerAPI.kt:362) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.addPlayerExpForce(PlayerAPI.kt:185) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.internal.command.subcommand.ExpCommand$exp$1$1$2$1.invoke(ExpCommand.kt:21) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.internal.command.subcommand.ExpCommand$exp$1$1$2$1.invoke(ExpCommand.kt:20) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandExecutor.exec(CommandExecutor.kt:11) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:87) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute(CommandBase.kt:100) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:40) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda$0(BukkitCommand.kt:74) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 15 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:5 Missing close quote
1400"
     ^
        at jdk.nashorn.internal.parser.Lexer.error(Lexer.java:1700) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.Lexer.scanString(Lexer.java:988) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.Lexer.lexify(Lexer.java:1611) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.AbstractParser.getToken(AbstractParser.java:132) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.AbstractParser.nextToken(AbstractParser.java:213) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.AbstractParser.nextOrEOL(AbstractParser.java:170) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.AbstractParser.next(AbstractParser.java:157) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:281) ~[nashorn.jar:?]
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284) ~[nashorn.jar:?]
        at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:651) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:493) ~[nashorn.jar:?]
        at jdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:182) ~[nashorn.jar:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common5.NashornCompilerKt.compileJS(NashornCompiler.kt:31) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.LevelAPI.getLvlExp(LevelAPI.kt:146) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.LevelAPI.getLevelExp(LevelAPI.kt:70) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.checkCondition(PlayerAPI.kt:324) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.refreshLevel(PlayerAPI.kt:362) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.api.PlayerAPI.addPlayerExpForce(PlayerAPI.kt:185) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.internal.command.subcommand.ExpCommand$exp$1$1$2$1.invoke(ExpCommand.kt:21) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.internal.command.subcommand.ExpCommand$exp$1$1$2$1.invoke(ExpCommand.kt:20) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandExecutor.exec(CommandExecutor.kt:11) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:87) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute$process(CommandBase.kt:78) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.component.CommandBase.execute(CommandBase.kt:100) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:40) ~[?:?]
        at com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda$0(BukkitCommand.kt:74) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 15 more`

**Comment by CPJiNan** [comment]
@Eplge627 
实际测试添加 Long 范围的经验时似乎并未出现该问题。请添加 QQ 2759278070 以便提供更多详细错误信息。

**Comment by Eplge627** [comment]
> @Eplge627 实际测试添加 Long 范围的经验时似乎并未出现该问题。请添加 QQ 2759278070 以便提供更多详细错误信息。

哦才发现是level文件夹的配置文件写错了，建议加个提示，重载插件的时候也没有WARN
