### ISSUE TITLE
在滑动快捷栏的时候报错

### ISSUE THREAD

**Issue by Radiar77** [CPJiNan/AkariLevel#16]
服务端：paper 1.21-130
每次更改所选择的快捷栏格（1-9）时，控制台会报下面这段
直接用其它物品代替现有的主手物品时不会触发
Could not pass event PlayerItemHeldEvent to AkariLevel v4.0.6 java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.module.ui.ClickListener.onItemHeld(ClickListener.kt:134) ~[?:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:107) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:105) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:75) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
	at AkariLevel-4.0.6.jar/com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:55) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2061) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by CPJiNan** [comment]
该问题可能是 AkariLevel 在尚未支持 1.21 的 Taboolib 版本安装了似乎并未使用的 UI 模块导致。
新版本可能会尝试更新 Taboolib 版本并卸载 UI 模块。
