### ISSUE TITLE
paper-1.21.1运行最新版本的时候输入指令提示未知指令

### ISSUE THREAD

**Issue by Eplge627** [CPJiNan/AkariLevel#17]
之前在1.12.2服务端运行的时候可以正常使用
<img width="658" alt="{B1788EB5-D656-4A70-9723-B56F2B8C7275}" src="https://github.com/user-attachments/assets/e0927674-3227-41bd-a72b-c0f6e4da221f">
<img width="339" alt="{10B8E635-B9B6-4958-A460-0FD91593A966}" src="https://github.com/user-attachments/assets/355d57bd-50ed-4bc7-a1ed-e5e45f67c65f">

**Comment by Eplge627** [comment]
<img width="180" alt="{54D270DF-A6C7-4C14-B41D-CB4BFB1385B1}" src="https://github.com/user-attachments/assets/e495167d-b71a-479d-b5e0-902c7adc3265">
插件加载时报了个WARN
正在加载 AkariLevel... 4.0.6
[19:41:51 WARN]: com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.ClassVisitException: class com.github.cpjinan.plugin.akarilevel.taboolib.module.nms.MinecraftVersion#init: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=NONE), AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), com.github.cpjinan.plugin.akarilevel.taboolib.module.kether.KetherLoader@2d3b159b, com.github.cpjinan.plugin.akarilevel.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@20d0e0f4, com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.command.SimpleCommandRegister@7ac6d2d3]} (LOAD)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:146)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:114)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:77)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.VisitorHandler.lambda$init$0(VisitorHandler.java:44)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.TabooLib$1.run(TabooLib.java:79)
[19:41:51 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:56)
[19:41:51 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.TabooLib.lifeCycle(TabooLib.java:56)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:73)
[19:41:51 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[19:41:51 WARN]:        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[19:41:51 WARN]:        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[19:41:51 WARN]:        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
[19:41:51 WARN]:        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
[19:41:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
[19:41:51 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[19:41:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[19:41:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:41:51 WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:211)
[19:41:51 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[19:41:51 WARN]:        at AkariLevel-4.0.6.jar//com.github.cpjinan.plugin.akarilevel.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:144)
[19:41:51 WARN]:        ... 18 more

**Comment by Eplge627** [comment]
问题已解决，建议插件能支持Paper端awa
换成spigot端就没问题了
